server:
  port: 9595

spring:
  application:
    name: hepsi-recommendation-etl
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/data-db
    username: postgres
    password: 123456
  batch:
    initialize-schema: NEVER
    job:
      enabled: true
  liquibase:
    change-log: classpath:/db/changelog/db.changelog.xml

recommendation:
  page-size: 1
  personalized-recommendations-chunk-size: 300
  user-preferred-category-limit: 3
  category-product-limit: 10
