server:
    port: 9597

spring:
  application:
    name: hepsi-recommendation-stream-reader
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/data-db
    username: postgres
    password: 123456
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      bootstrap-servers: localhost:9092
      group-id: hepsi-recommendation-views-group
      enabled: true
      topic-name: hepsi.recommendation.views

